# Generated by Django 3.2.9 on 2022-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serch_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(max_length=100)),
                ('used_search_engine', models.CharField(max_length=100)),
                ('what_results', models.CharField(max_length=100)),
                ('what_time', models.TimeField(null=True)),
                ('what_date', models.DateField(null=True)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
